### ISSUE TITLE
Spelling suggestions

### ISSUE THREAD

**Issue by tvanderstad** [helix-editor/spellbook#2]
Hey there! I'm looking to add spell checking to [Lockbook](https://github.com/lockbook/lockbook), a note taking app I'm writing in Rust. I saw some commits related to suggestions so I went ahead pulled your master branch and POC'd it in my app. You can find a 5s video demo on this [PR](https://github.com/lockbook/lockbook/pull/3046).

I had to replace [this](https://github.com/helix-editor/spellbook/blob/master/src/suggester.rs#L83) `todo!()` with `{}` but then everything seemed to be working great. The suggestions are good and Spellbook spell-checks my longest note, a 35kb markdown file, in ~1ms.

When will spelling suggestions be available through crates.io?

**Comment by the-mikedavis** [comment]
Glad Spellbook is looking promising so far!

I can't give a timeline but the suggestion interface is my current focus when I find time to work on Spellbook. (I've been away for a few weeks on vacation but should get back to working on Spellbook sooner rather than later.) I'd estimate that `suggester.rs` currently around half finished - the functions are there to make simple edits to words but not all of the higher level logic is there yet, and there are some other routines for making higher quality suggestions that aren't yet implemented. Once all of that is in place there will be some testing to do but then I'll publish a v0.2.0 release up to crates.io

**Comment by the-mikedavis** [comment]
Ok with the latest commits (in particular 3f0aa5cab046) the suggester should be finished now :tada:

I'll be testing manually for the next few days and look at cutting a release at the end of the week. If you'd like to test drive the change before I publish it to crates, please let me know if you run into any panics. (There are tests for the new suggestion code but coverage isn't 100%.)

**Comment by the-mikedavis** [comment]
0.2.0 is now published :rocket:

https://github.com/helix-editor/spellbook/releases/tag/v0.2.0, https://crates.io/crates/spellbook/0.2.0
